### ISSUE TITLE
AttributeError: type object 'Language' has no attribute 'component'

### ISSUE THREAD

**Issue by AR-9191** [medianeuroscience/emfdscore#7]
I'm getting the following error on Mac both when running in jupyter and in the terminal. Any ideas?

Command:
emfdscore covid_tweets.csv all-sent.csv bow emfd all sentiment

Error:
Traceback (most recent call last):
  File "/Users/***/opt/anaconda3/bin/emfdscore", line 7, in <module>
    from emfdscore.scoring import score_docs, pat_docs
  File "/Users/***/opt/anaconda3/lib/python3.7/site-packages/emfdscore/scoring.py", line 25, in <module>
    @Language.component("mfd_tokenizer")
AttributeError: type object 'Language' has no attribute 'component'

**Comment by AR-9191** [comment]
Also when running in a virtual environment I'm getting a different error:


Traceback (most recent call last):
  File "/Users/__/opt/anaconda3/envs/emfd/bin/emfdscore", line 67, in <module>
    df = score_docs(csv,DICT_TYPE,PROB_MAP,SCORE_METHOD,OUT_METRICS,num_docs)
  File "/Users/__/opt/anaconda3/envs/emfd/lib/python3.7/site-packages/emfdscore/scoring.py", line 359, in score_docs
    scored_docs.append(nlp(row))
  File "/Users/__/opt/anaconda3/envs/emfd/lib/python3.7/site-packages/spacy/language.py", line 978, in __call__
    doc = self.make_doc(text)
  File "/Users/__/opt/anaconda3/envs/emfd/lib/python3.7/site-packages/spacy/language.py", line 1056, in make_doc
    if len(text) > self.max_length:
TypeError: object of type 'float' has no len()

**Comment by fhopp** [comment]
This appears to be a problem with the format of your input data, rather than with emfdscore itself. 
To make sure this is the cast, please first try to run your command on the template_input.csv data that comes with emfdscore (in your case, this file should be under "/Users//opt/anaconda3/envs/emfd/lib/python3.7/site-packages/emfdscore/template_input.csv). Does the command work when running on the template data?

**Comment by AR-9191** [comment]
yes that worked, thank you!

**Comment by deliapxq** [comment]
Hi there! I'm facing the same error, but I'm using the template_input.csv data as in the tutorial (I'm running the code in the tutorial as is!)

AttributeError                            Traceback (most recent call last)
<ipython-input-10-bc173c26879d> in <module>
----> 1 from emfdscore.scoring import score_docs
      2 
      3 num_docs = len(nsd)
      4 
      5 DICT_TYPE = 'emfd'

~\anaconda3\envs\emfd\lib\site-packages\emfdscore\scoring.py in <module>
     23 
     24 # BoW Scoring #
---> 25 @Language.component("mfd_tokenizer")
     26 def tokenizer(doc):
     27 

AttributeError: type object 'Language' has no attribute 'component'

Thank you!

**Comment by fhopp** [comment]
Hi @deliapxq , 
the @language decorator was added in a more recent version of spaCy that we use to parse texts. 
Would you mind simply reinstalling eMFDscore in a fresh enviornment as explained in the README and then trying it again?
Please let me know if that fixes it!

**Comment by deliapxq** [comment]
hi @fhopp, installing in a new environment did help :) thanks a lot!

**Comment by ongism** [comment]
Hi @fhopp 

I keep getting the same error when I launch this part of the syntax: 

### from emfdscore.scoring import score_docs 

num_docs = len(template_input)

DICT_TYPE = 'emfd'
PROB_MAP = 'all'
SCORE_METHOD = 'bow'
OUT_METRICS = 'sentiment'
OUT_CSV_PATH = 'all-sent.csv'

df = score_docs(template_input,DICT_TYPE,PROB_MAP,SCORE_METHOD,OUT_METRICS,num_docs)
df.to_csv(OUT_CSV_PATH, index=False) ###

**"[E005] Pipeline component 'mfd_tokenizer' returned <class 'list'> instead of a Doc. If you're using a custom component, maybe you forgot to return the processed Doc?"**

Happens on Google Colab as well, and with the tuotrial in the folder. 

Not sure what's the issue here--can you advice on how to proceed? 

Thanks!
